---
title: "Intro Figure"
output: html_document
date: "2022-11-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load Libraries
```{r}
library(tigris)
library(sf)
library(ggplot2)
library(dplyr)
library(haven)
library(here)
library(janitor)
library(readxl)
```

Define Variables
```{r}
# How much to space out layers
y_int <- .5 

# Color Palette
fill_palette <- "Spectral"
```

Read in Data
```{r}

# County polygons from tigris package
counties <- counties() %>%
  mutate(poly_id = as.numeric(GEOID)) %>% 
  filter(poly_id < 60000) %>%
  filter(!poly_id %in% 2000:2999, !poly_id %in% 15000:15999) %>% 
  st_as_sf()

# Deaths Data from Olivier Deschenes 
deaths_data <- read_dta(here("data/mortality_and_population/CountyYearMonth_1999_2019.dta")) %>% 
  filter(year == 2019, month %in% c(6, 7, 8)) %>% 
  rename(poly_id = countycode)


# Population Data from 2000 to 2010 from census estimates
pop_2000s <- read.csv(here("data/mortality_and_population/co-est00int-tot.csv")) %>%
  clean_names() %>% 
  mutate(county_state = paste0(".", ctyname, ", ", stname))

# Population Data from 2011 to 2019 from census estimates 
pop_data <- read_xlsx(here("data/mortality_and_population/co-est2019-annres.xlsx"), skip = 3) %>% 
  clean_names() %>% 
  rename(county_state = 1) %>% 
  dplyr::select(county_state, x2019) %>% 
  left_join(pop_2000s, by = "county_state") %>% 
  mutate(poly_id = as.numeric(paste0(state, sprintf("%03d", county)))) %>% 
  dplyr::select(poly_id, x2019) %>% 
  filter(!is.na(poly_id))

# Merge polyogns, deaths, and population
mortality_data <- right_join(deaths_data,  pop_data, by = "poly_id") %>% 
  mutate(mortality = deaths / x2019) %>% 
  inner_join(counties, by = "poly_id") %>% 
  st_as_sf()

# Raster brick 1 year of temp data !!!This file is to big for the github repo, you must have it in your local data folder!!!
data <- crop(brick(here("data", "rasters", "era5_temp_2020.nc")), extent(st_shift_longitude(counties)))
data <- data - 273.15

```


Define Rotation Functions (This Code is from Stefan Junger https://stefanjuenger.github.io/gesis-workshop-geospatial-techniques-R/slides/2_4_Advanced_Maps_II/2_4_Advanced_Maps_II.html#8)
```{r}
rotate_data <- function(data, x_add = 0, y_add = 0) {
  
  # shear_matrix <- function(){ matrix(c(1,1,1,1), 2, 2) }
  shear_matrix <- function(){ matrix(c(2, 1.2, 0, 1), 2, 2) }
  # rotate_matrix <- function(x){ 
  #   matrix(c(1,1,1,1), 2, 2) 
  # }
  
  rotate_matrix <- function(x){
    matrix(c(cos(x), sin(x), -sin(x), cos(x)), 2, 2)
  }
  data %>% 
    dplyr::mutate(
      geometry = .$geometry * shear_matrix() * rotate_matrix(pi/20) + c(x_add, y_add)
    )
}

rotate_data_geom <- function(data, x_add = 0, y_add = 0) {
  shear_matrix <- function(){ matrix(c(2, 1.2, 0, 1), 2, 2) }
  
  rotate_matrix <- function(x) { 
    matrix(c(cos(x), sin(x), -sin(x), cos(x)), 2, 2) 
  }
  data %>% 
    dplyr::mutate(
      geom = .$geom * shear_matrix() * rotate_matrix(pi/20) + c(x_add, y_add)
    )
}
```


Create Hourly Raster Brick
```{r}
# Blank Plot
hourly <- ggplot()

# While Loop to Keep Adding Layers to Plot
i <- 4331 
while(i <= 4340){
  
  # Read layer from data
  a <- raster(data, layer = i) %>% 
    rasterToPolygons(na.rm = TRUE) %>% 
    st_as_sf() %>% 
    rename(value = 1) %>% 
    st_as_sf()
  
  hourly <- hourly + 
    geom_sf(data = a %>% rotate_data(y_add = 3*y_int*i), mapping = aes(fill = value), size = 2, color = "black") +
    geom_sf(data = a %>% rotate_data(y_add = 3*y_int*i), mapping = aes(fill = value), color = NA)
  i = i + 1
}

```



Polish Hourly Raster Brick
```{r}

axis_text_size <- 12

hourly <- hourly +
  scale_fill_distiller(palette = fill_palette, 
                       direction = -1,
                       breaks = c(seq(0, 40, 10)),
                       limits = c(0, 40)) +
  labs(y = "Hours",
       x = NULL,
       fill = "Degrees celsius") +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = axis_text_size),
        legend.position = c(0.8, 0.7),
        legend.direction = "horizontal",
        plot.caption = element_text(size = axis_text_size, face = "plain", hjust = .5),
        plot.background = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank()) +
  guides(fill = guide_colourbar(title.position = "top",
                                frame.colour = "darkgray", ticks.colour = "black"))



ggsave(hourly + theme(legend.position = "none"),
       filename = here("figs/intro_fig/temperature_stack.png"),
       width = 7,
       height = 5,
       units = "in",
       dpi = 300)

ggsave(hourly + theme(legend.position = "none"),
       filename = here("figs/intro_fig/temperature_stack.pdf"),
       width = 7,
       height = 5,
       units = "in",
       dpi = 300)

fig5a_l <- get_legend(hourly)

ggsave(fig5a_l,
       filename = here("figs/intro_fig/temperature_stack_l.png"),
       # width = 7,
       # height = 5,
       # units = "in",
       dpi = 300)

ggsave(fig5a_l,
       filename = here("figs/intro_fig/temperature_stack_l.pdf"),
       # width = 7,
       # height = 5,
       # units = "in",
       dpi = 300)




```

Create stack of monthly mortality data
```{r}
mortality_plot <- ggplot()

i <- 8
while(i >= 6){

  
  a <- mortality_data %>% 
    filter(month == i) %>% 
    st_as_sf() 
  
  box <- st_make_grid(a, n = 1) %>% 
    data.frame() %>% 
    st_as_sf() %>% 
    rotate_data(y_add = 10*y_int*(9 - i))
  
  a <- a %>%
    rotate_data(y_add = 10*y_int*(9 - i))
  
  mortality_plot <- mortality_plot +
    geom_sf(data = box, size = .1, color = "black", fill = "white") +
    #geom_sf(data = a, mapping = aes(fill = order_1), size = 2, color = "black") +
    geom_sf(data = a, mapping = aes(fill = 1000*mortality), color = NA) +
    geom_sf(data = box, size = 1, color = "black", fill = NA)
  
  i = i - 1
}
```


Polish stack of monthly mortality data
```{r}
mortality_plot <- mortality_plot +
  scale_fill_gradient2(low = "white",
                       high = "firebrick3", 
                       midpoint = 0.2, 
                       na.value = "grey95",
                       breaks = c(1,2,3)) +
  labs(fill = "Deaths per 1,000\nindividuals",
       y = "Months",
       x = NULL) +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = axis_text_size),
        legend.position = c(0.7, 0.7),
        legend.direction = "horizontal",
        plot.caption = element_text(size = axis_text_size, face = "plain", hjust = .5),
        plot.background = element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_blank()) +
  guides(fill = guide_colourbar(title.position = "left",
                                frame.colour = "darkgray", ticks.colour = "black"))
  

ggsave(mortality_plot + theme(legend.position = "none"),
       filename = here("figs/intro_fig/mortality_stack.png"),
       # width = 7,
       # height = 5,
       # units = "in",
       dpi = 300)

ggsave(mortality_plot + theme(legend.position = "none"),
       filename = here("figs/intro_fig/mortality_stack.pdf"),
       # width = 7,
       # height = 5,
       # units = "in",
       dpi = 300)

fig5b_l <- get_legend(mortality_plot)

ggsave(fig5b_l,
       filename = here("figs/intro_fig/mortality_stack_l.png"),
       # width = 7,
       # height = 5,
       # units = "in",
       dpi = 300)

ggsave(fig5b_l,
       filename = here("figs/intro_fig/mortality_stack_l.pdf"),
       # width = 7,
       # height = 5,
       # units = "in",
       dpi = 300)



```

