---
title: "Overlay Weights Figure"
output: html_document
date: "2022-10-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

Load Packages
```{r}
library(stagg)
library(tidyverse)
library(here)
library(raster)
library(sf)
library(gridExtra)
library(tigris)
library(ggpubr)
library(data.table)
```


Define Variables
```{r}
# Location selection
state_abb <- "CA"
county_geoid <- "06107"
# Color Scheme
polygon_fill <- "white"
cropland_fill <- "gold"
grid_color <- "grey"
w_area_fill <- "#61B1FF"
combined_fill <- "#7fb17f"

axis_text_size <- 12

grid_width <- 0.65
poly_width <- 0.8

```


Read in Data
```{r}
# Polygons for whole state
state_counties <- counties(state_abb)
# Polygon only of one county
county <- state_counties %>%  # We are using one county from the tigris package
  filter(GEOID == county_geoid) %>% 
  st_as_sf() 

# Get the extent of the county with buffer
county_extent0 <- extent(county)
county_extent0@xmin <- county_extent0@xmin - 0.5
county_extent0@xmax <- county_extent0@xmax + 0.5
county_extent0@ymin <- county_extent0@ymin - 0.5
county_extent0@ymax <- county_extent0@ymax + 0.5
 

 
# !!!These files are too large to be stored on github and must be manually copied to your directory's data folder!!!

# Cropland to use as secondary weights
cropland_raster <- crop(raster(here("data/rasters/cropland_NW_2015.tif")), county_extent0)
```


Run Stagg
```{r}
# Generate a table of era5 scale cropland weights
cropland_table <- secondary_weights(secondary_raster = cropland_raster, extent = county_extent0) 

# Generate a table of overlay weights
overlay <- overlay_weights(polygons = county, polygon_id_col ="GEOID", secondary_weights = cropland_table) %>% 
  rename(combined_weight = weight)

overlay_extent <- extent(overlay)
```

Raster Plot
```{r}

# Transform fine resolution raster into a data frame for plotting
cropland_df <- as.data.frame(cropland_raster, xy = TRUE)

# cropland_df_crop <- cropland_df %>%
#   filter(x >= -119.63 & x <= -117.9) %>%
#   filter(y >= 35.63 & y <= 36.88)

cropland_df_crop <- cropland_df %>%
  filter(x >= -119.63 & x <= -117.87) %>%
  filter(y >= 35.63 & y <= 36.88)

cropland_table_crop <- cropland_table %>%
  filter(x >= -119.5 & x <= -118) %>%
  filter(y >= 35.75 & y <= 36.75)

cropland_fig <- ggplot() +
  # geom_tile(data = cropland_df, aes(x,y, fill = as.factor(cropland_NW_2015))) +
  geom_tile(data = cropland_df_crop, aes(x,y, fill = as.factor(cropland_NW_2015))) +
  geom_sf(data = county, alpha = 0, lwd = poly_width) +
  geom_tile(data = cropland_table_crop, mapping = aes(x = x, y = y), 
            alpha = 0, lwd = grid_width, color = grid_color)  +
  labs(caption = "Cropland raster") +
  scale_fill_manual(values = c("0" = "white",
                              "1" = cropland_fill)) +
  # xlim(c(-120, -118.5)) +
  # ylim(c(35, 37)) +
  # ylim(c(overlay_extent@ymin - 0.125, overlay_extent@ymax + 0.125)) +
  # xlim(c(min(cropland_table$x) - 0.125, max(cropland_table$x) + 0.125)) +
  # ylim(c(min(cropland_table$y) - 0.125, max(cropland_table$y) + 0.125)) +
  theme_void() +       
  theme(legend.position = "none",
        plot.background = element_blank(),
        plot.caption = element_text(hjust = 0.5, size = axis_text_size),
        plot.margin = margin(b = 10))
  
ggsave(cropland_fig,
       # filename = here("figs/overlay_weights_fig/raster_fig.png"),
       filename = here("figs/overlay-weights-fig/raster_fig.png"),
       width = 3,
       height = 3,
       units = "in",
       dpi = 300)

ggsave(cropland_fig,
       # filename = here("figs/overlay_weights_fig/raster_fig.pdf"),
       filename = here("figs/overlay-weights-fig/raster_fig.pdf"),
       width = 3,
       height = 3,
       units = "in",
       dpi = 300)

```

Plot of Resampled Secondary Weights
```{r}
resamp_sec_weights_fig <- ggplot() +
  geom_tile(data = cropland_table_crop, mapping = aes(x = x, y = y, fill = weight), size = grid_width, color = grid_color) +
  geom_sf(data = county, alpha = 0, lwd = poly_width) +
  scale_fill_gradient(low = "white",
                      high = cropland_fill,
                      breaks = c(0, 0.2, 0.4, 0.60, 0.8),
                      limits = c(min(cropland_table$weight ), 0.8),
                      guide = guide_colorbar(frame.colour = "black",
                                             ticks.colour = "black",
                                             ticks = TRUE)) +
  theme_void() +
  labs(fill = "Resampled crop weights",
       x = NULL,
       y = NULL) +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.title = element_text(size = axis_text_size),
        legend.title = element_text(size = axis_text_size),
        legend.key.width = unit(1, "cm"),
        legend.title.align = 0.5,
        plot.margin = margin(b = 10)) +
  guides(fill = guide_colourbar(title.position = "bottom",
                                frame.colour = "darkgray", ticks.colour = "black"))

ggsave(resamp_sec_weights_fig,
       # filename = here("figs/overlay_weights_fig/perc_coverage_sweight.png"),
       filename = here("figs/overlay-weights-fig/perc_coverage_sweight.png"),
       width = 5,
       height = 5,
       units = "in",
       dpi = 300)
ggsave(resamp_sec_weights_fig,
       # filename = here("figs/overlay_weights_fig/perc_coverage_sweight.pdf"),
       filename = here("figs/overlay-weights-fig/perc_coverage_sweight.pdf"),
       width = 3,
       height = 3,
       units = "in")
```

Sole Polygon and Grid Plot
```{r}
admin_region_fig <- 
  ggplot() +
  labs(caption = "County polygon") +
  geom_sf(data = county, fill = w_area_fill, color = "black", alpha = 0.6, lwd = poly_width) +
  geom_tile(data = cropland_table_crop, mapping = aes(x = x, y = y), alpha = 0, size = grid_width, color = grid_color) +
  theme_void() +
  theme(plot.caption = element_text(hjust = 0.5, size = axis_text_size),
        plot.margin = margin(b = 10))

ggsave(admin_region_fig,
       # filename = here("figs/overlay_weights_fig/admin_region_fig.png"),
       filename = here("figs/overlay-weights-fig/admin_region_fig.png"),
       width = 3,
       height = 3,
       units = "in",
       dpi = 300)

ggsave(admin_region_fig,
       # filename = here("figs/overlay_weights_fig/admin_region_fig.pdf"),
       filename = here("figs/overlay-weights-fig/admin_region_fig.pdf"),
       width = 3,
       height = 3,
       units = "in",
       dpi = 300)
  
```


Area Weights Plot
```{r}
# Same idea as previous image
weight_area_fig <-
  ggplot() +
  geom_tile(data = overlay, mapping = aes(x = x, y = y, fill = w_area), size = grid_width, color = grid_color) +
  scale_fill_gradient(low = "white",
                      high = w_area_fill,
                      breaks = c(0, 0.025, 0.05),
                      limits = c(0, 0.05),
                      guide = guide_colorbar(frame.colour = "black",
                                             ticks.colour = "black",
                                             ticks = TRUE)) +
  geom_sf(data = st_shift_longitude(county), alpha = 0, lwd = poly_width) +
  theme_void() +
  labs(fill = "Fraction of total county \narea captured by cell",
       x = NULL,
       y = NULL) +
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.title = element_text(size = axis_text_size),
        legend.title = element_text(size = axis_text_size),
        legend.key.width = unit(1, "cm"),
        legend.title.align = 0.5,
        plot.margin = margin(b = 10)) +
  guides(fill = guide_colourbar(title.position = "bottom",
                                frame.colour = "darkgray", ticks.colour = "black"))

ggsave(weight_area_fig,
       # filename = here("figs/overlay_weights_fig/weighted_area_fig.png"),
       filename = here("figs/overlay-weights-fig/weighted_area_fig.png"),
       width = 5,
       height = 5,
       units = "in",
       dpi = 300)
ggsave(weight_area_fig,
       # filename = here("figs/overlay_weights_fig/weighted_area_fig.pdf"),
       filename = here("figs/overlay-weights-fig/weighted_area_fig.pdf"),
       width = 5,
       height = 5,
       units = "in",
       dpi = 300)
```

Cropland Weights Normalized by Area
```{r}
# Same plot as before but using weight instead of w_area
combined_weight_fig <- 
  ggplot() +
  geom_tile(data = overlay, mapping = aes(x = x, y = y, fill = combined_weight), size = grid_width, color = grid_color) +
  scale_fill_gradient(low = "white",
                      high = combined_fill,
                      breaks = c(0, 0.05, 0.10, 0.15, 0.20, 0.25),
                      limits = c(min(overlay$combined_weight), 0.25),
                      guide = guide_colorbar(frame.colour = "black",
                                             ticks.colour = "black",
                                             ticks = TRUE,
                                             barwidth = 10)) +
  geom_sf(data = st_shift_longitude(county), alpha = 0, lwd = poly_width) +
  #geom_label(data = overlay, mapping = aes(x = x, y = y, label = weight)) +
  theme_void() +
  labs(fill = "Fraction of total cropland\nin county captured by cell",
       x = NULL,
       y = NULL) +
   theme(legend.position = "bottom",
        legend.direction = "horizontal",
        axis.title = element_text(size = axis_text_size),
        legend.title = element_text(size = axis_text_size),
        legend.key.width = unit(1, "cm"),
        legend.title.align = 0.5,
        plot.margin = margin(b = 10)) +
  guides(fill = guide_colourbar(title.position = "bottom",
                                frame.colour = "darkgray", ticks.colour = "black"))


ggsave(combined_weight_fig,
       # filename = here("figs/overlay_weights_fig/combined_weight_fig.png"),
       filename = here("figs/overlay-weights-fig/combined_weight_fig.png"),
       width = 3,
       height = 3,
       units = "in",
       dpi = 300)
ggsave(combined_weight_fig,
       # filename = here("figs/overlay_weights_fig/combined_weight_fig.pdf"),
       filename = here("figs/overlay-weights-fig/combined_weight_fig.pdf"),
       width = 3,
       height = 3,
       units = "in",
       dpi = 300)
```

