---
title: "Demonstration Figures"
output: html_document
date: "2022-11-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Load Packages
```{r}
library(stagg)
library(tidyverse)
library(raster)
library(sf)
library(haven)
library(here)
library(tigris)
library(data.table)
library(janitor)
library(broom)
library(readxl)
library(lfe)
```

Read in Data, Clean, and Merge
```{r}
# Data on deaths
deaths <- read_dta(here("data/CountyYearMonth_1999_2019.dta")) %>% 
  as.data.table() %>% 
  filter(!is.na(countycode), !is.na(deaths)) %>% # Remove any rows with na in deaths column or in county code
  rename(poly_id = countycode)

# Population data from census estimates
pop_2000s <- read.csv(here("data/co-est00int-tot.csv")) %>%
  clean_names()

pop_2010s <- read_xlsx(here("data/co-est2019-annres.xlsx"), skip = 3) %>% 
  clean_names() %>% 
  rename(county_state = 1)

# Clean and merge population data
pop_all <- pop_2000s %>% 
  mutate(county_state = paste0(".", ctyname, ", ", stname)) %>% 
  right_join(pop_2010s, by = "county_state") %>% 
  rename(x2000 = popestimate2000, x2001 = popestimate2001, x2002 = popestimate2002,
         x2003 = popestimate2003, x2004 = popestimate2004, x2005 = popestimate2005,
         x2006 = popestimate2006, x2007 = popestimate2007, x2008 = popestimate2008,
         x2009 = popestimate2009) %>% 
  mutate(poly_id = as.numeric(paste0(state, sprintf("%03d", county)))) %>% 
  dplyr::select(poly_id, x2000, x2001, x2002, x2003, x2004, x2005, x2006, x2007, x2008,
         x2009, x2010, x2011, x2012, x2013, x2014, x2015, x2016, x2017, x2018, x2019) %>% 
  pivot_longer(cols = 2:21, names_to = "year", values_to = "population") %>% 
  mutate(year = as.numeric(substr(year, start = 2, stop = 5)))

# Counties and their states (use to correctly identify each county's state)
county_states = counties()

county_states <- county_states %>% 
  clean_names() %>% 
  as.data.frame() %>% 
  mutate(poly_id = as.numeric(geoid)) %>%  # Assuming same county fps system in tigris counties and health data
  dplyr::select(statefp, poly_id)

# Binned temperature
temp_bin <- rbind(fread(here("data/temp_binned_2000_2004_US_counties_ERA5_pop_weights.csv")),
                  fread(here("data/temp_binned_2005_2009_US_counties_ERA5_pop_weights.csv")),                                              fread(here("data/temp_binned_2010_2014_US_counties_ERA5_pop_weights.csv")),
                  fread(here("data/temp_binned_2015_2019_US_counties_ERA5_pop_weights.csv")))

# Polynomial Temperature
temp_poly <- rbind(
  fread(here("data/temp_polynomial_2000_2004_US_counties_ERA5_pop_weights.csv")),
  fread(here("data/temp_polynomial_2005_2009_US_counties_ERA5_pop_weights.csv")),
  fread(here("data/temp_polynomial_2010_2014_US_counties_ERA5_pop_weights.csv")),
  fread(here("data/temp_polynomial_2015_2019_US_counties_ERA5_pop_weights.csv"))) %>% 
  rename(order_1_temp = order_1, order_2_temp = order_2, order_3_temp = order_3,
         order_4_temp = order_4, order_5_temp = order_5) # To distinguish from prcp

# Spline Temperature
temp_spline <- rbind(
  fread(here("data/temp_spline_2000_2004_US_counties_ERA5_pop_weights.csv")),
  fread(here("data/temp_spline_2005_2009_US_counties_ERA5_pop_weights.csv")),
  fread(here("data/temp_spline_2010_2014_US_counties_ERA5_pop_weights.csv")),
  fread(here("data/temp_spline_2015_2019_US_counties_ERA5_pop_weights.csv")))

# Quadratic Precipitation
prcp_poly <- rbind(
  fread(here("data/prcp-polynomial-2000-2004-US-counties-prcp-era5-pop_weights.csv")),
  fread(here("data/prcp-polynomial-2005-2009-US-counties-prcp-era5-pop_weights.csv")),
  fread(here("data/prcp-polynomial-2010-2014-US-counties-prcp-era5-pop_weights.csv")),
  fread(here("data/prcp-polynomial-2015-2019-US-counties-prcp-era5-pop_weights.csv"))) %>% 
  rename(order_1_prcp = order_1,
         order_2_prcp = order_2) # to distinguish between temp polynomial and prcp polynomial

# Merge all data together
all_data <- inner_join(temp_bin, prcp_poly, by = c("year", "month", "poly_id")) %>% 
  full_join(temp_poly, by = c("year", "month", "poly_id")) %>% 
  full_join(temp_spline, by = c("year", "month", "poly_id")) %>% 
  inner_join(deaths, by = c("year", "month", "poly_id")) %>% 
  inner_join(county_states, by = "poly_id") %>% 
  inner_join(pop_all, by = c("poly_id", "year")) %>% 
  mutate(mortality = deaths / population)

```

Regression
```{r}
# Define formula to regress mortality on temperature bins, controlling for precipitation (quadratic) with fixed effects for county_month and state_year
bins <- c("bin_ninf_to_n10", "bin_n10_to_n5", "bin_n5_to_0", "bin_0_to_5", "bin_5_to_10", "bin_10_to_15", "bin_20_to_25", "bin_25_to_30", "bin_30_to_inf")

bin_string <- ""
i <- 1
while(i <= length(bins)){
  if(i != length(bins)){
    bin_string <- paste0(bin_string, bins[i], " + ")
  }
  else{
    bin_string <- paste0(bin_string, bins[i])
  }
  
  i = i + 1
}

bin_formula <- as.formula(paste0("log(mortality) ~ ", bin_string, " + order_1_prcp + order_2_prcp | as.factor(poly_id):as.factor(month) + as.factor(statefp):as.factor(year) | 0 | poly_id"))

bin_regression <- felm(bin_formula, all_data)


poly_string <- "order_1_temp + order_2_temp + order_3_temp + order_4_temp" # Order 5 coefficient not significant, removed and re-ran, order 4 was significant

poly_formula <- as.formula(paste0("log(mortality) ~ ", poly_string, "+ order_1_prcp + order_2_prcp | as.factor(poly_id):as.factor(month) + as.factor(statefp):as.factor(year) | 0 | poly_id"))

poly_regression <- felm(poly_formula, all_data)

spline_formula <- as.formula(paste0("log(mortality) ~ value + term_1 + order_1_prcp + order_2_prcp | as.factor(poly_id):as.factor(month) + as.factor(statefp):as.factor(year) | 0 | poly_id"))

spline_regression <- felm(spline_formula, all_data)


```


Plot Regression Results
```{r}
# Turn regression into a data frame to extract coefficients and plot
bin_plot_data <- tidy(bin_regression, conf.int = TRUE)

bin_plot_data <- bin_plot_data %>% 
  filter(term %in% bins) %>% 
  add_row(term = "bin_15_to_20", estimate = 0, conf.low = 0, conf.high = 0) %>% 
  mutate(graph_index = c(-12.5,-7.5, -2.5, 2.5, 7.5, 12.5, 22.5, 27.5,32.5, 17.5))

poly_plot_data <- tidy(poly_regression, conf.int = TRUE)

poly_plot_function <- function(x){
  poly_plot_data$estimate[4]*(x)^4 + 
  poly_plot_data$estimate[3]*x^3 +
  poly_plot_data$estimate[2]*x^2 +
  poly_plot_data$estimate[1]*x -
  poly_plot_data$estimate[4]*17.5^4 - 
  poly_plot_data$estimate[3]*17.5^3 -
  poly_plot_data$estimate[2]*17.5^2 -
  poly_plot_data$estimate[1]*17.5}

spline_plot_data <- tidy(spline_regression, conf.int = TRUE)

spline_knot_locs <- c(-2.5, 17.5, 27.5)

spline_term_calc_function <- function(x){  
  part1 <- ifelse((x - spline_knot_locs[1]) > 0,
                   (x - spline_knot_locs[1])^3, 0)

  part2 <- (ifelse((x - spline_knot_locs[length(spline_knot_locs) - 1]) > 0,
                 (x - spline_knot_locs[length(spline_knot_locs) - 1])^3 *
                   ((spline_knot_locs[length(spline_knot_locs)] - spline_knot_locs[1]) / (spline_knot_locs[length(spline_knot_locs)] - spline_knot_locs[length(spline_knot_locs) - 1])), 0))


  part3 <- (ifelse((x - spline_knot_locs[length(spline_knot_locs)]) > 0,
                 (x - spline_knot_locs[length(spline_knot_locs)])^3 *
                   ((spline_knot_locs[length(spline_knot_locs) - 1] - spline_knot_locs[1]) / (spline_knot_locs[length(spline_knot_locs)] - spline_knot_locs[length(spline_knot_locs) - 1])), 0))
  
  return(spline_term <- part1 - part2 + part3)
  
}

spline_plot_function <- function(x){
  
    spline_plot_data$estimate[1]*x + 
    spline_plot_data$estimate[2]*spline_term_calc_function(x) - 
    spline_plot_data$estimate[1]*17.5 -
    spline_plot_data$estimate[2]*spline_term_calc_function(17.5)
  
}


spline_conf_low_function <- function(x){
  spline_plot_data$conf.low[1]*x + 
    spline_plot_data$conf.low[2]*spline_term_calc_function(x) - 
    spline_plot_data$conf.low[1]*17.5 -
    spline_plot_data$conf.low[2]*spline_term_calc_function(17.5)
}

spline_conf_high_function <- function(x){
  spline_plot_data$conf.high[1]*x + 
    spline_plot_data$conf.high[2]*spline_term_calc_function(x) - 
    spline_plot_data$conf.high[1]*17.5 -
    spline_plot_data$conf.high[2]*spline_term_calc_function(17.5)
}

ggplot() +
  geom_ribbon(data = bin_plot_data, mapping = aes(x = graph_index, ymin = conf.low, ymax = conf.high), color = "darkgrey", fill = "lightgrey") +
  geom_line(data = bin_plot_data, mapping = aes(x = graph_index, y = estimate), size = 1.25, color = "darkgreen") +
  geom_point(data = bin_plot_data, mapping = aes(x = graph_index, y = estimate), color = "black", size = 1.25) +
  theme_minimal() +
  scale_x_continuous(breaks = c(-12.5,-7.5, -2.5, 2.5, 7.5, 12.5, 17.5, 22.5, 27.5,32.5),
                     expand = c(0,0)) +
  scale_y_continuous(breaks = c(-.002, 0, .002, .004, .006),
                     limits = c(-.001, .005)) +
  labs(x = "Daily average temperature (C)",
       y = "Estimated Impact on Log Mortality") +
  theme(axis.line = element_line(color = "black"),
        plot.margin = margin(0, 7.5, 0, 0),
        panel.grid = element_blank(),
        axis.title = element_text(size = 16),
        axis.text = element_text(size = 12)) +
  geom_function(fun = poly_plot_function, color = "blue", size = 1.25) +
  geom_function(fun = spline_plot_function, color = "red", size = 1.25) #+
  #geom_function(fun = spline_conf_low_function, color = "red") +
  #geom_function(fun = spline_conf_high_function, color = "red")

  
```


