---
title: "Intro Figure"
output: html_document
date: "2022-11-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Note: This figure reuses the raster brick from the staggregate_fig.Rmd. Thus, this document only creates the stack of county mortality data

Load Libraries
```{r}
library(tigris)
library(sf)
library(ggplot2)
library(dplyr)
library(haven)
library(here)
library(janitor)
library(readxl)
```

Define Variables
```{r}
y_int <- .5
```

Read in Data
```{r}

# County polygons
ca_counties <- counties("CA") %>%
  mutate(poly_id = as.numeric(GEOID)) %>% 
  st_as_sf()

# Deaths Data
deaths_data <- read_dta(here("data/CountyYearMonth_1999_2019.dta")) %>% 
  filter(year == 2019, month %in% c(6, 7, 8)) %>% 
  rename(poly_id = countycode)


# We need pop data from 2000 to link county_state to GEOID
pop_2000s <- read.csv(here("data/co-est00int-tot.csv")) %>%
  clean_names() %>% 
  mutate(county_state = paste0(".", ctyname, ", ", stname))

# Population Data for 2019
pop_data <- read_xlsx(here("data/co-est2019-annres.xlsx"), skip = 3) %>% 
  clean_names() %>% 
  rename(county_state = 1) %>% 
  dplyr::select(county_state, x2019) %>% 
  left_join(pop_2000s, by = "county_state") %>% 
  mutate(poly_id = as.numeric(paste0(state, sprintf("%03d", county)))) %>% 
  dplyr::select(poly_id, x2019) %>% 
  filter(!is.na(poly_id))

# Merge polyogns, deaths, and population
mortality_data <- full_join(deaths_data,  pop_data, by = "poly_id") %>% 
  mutate(mortality = deaths / x2019) %>% 
  full_join(ca_counties, by = "poly_id") %>% 
  st_as_sf()

```


Define Rotation Functions (This Code is Not My Own, I don't understand it very well)
```{r}
rotate_data <- function(data, x_add = 0, y_add = 0) {
  
  # shear_matrix <- function(){ matrix(c(1,1,1,1), 2, 2) }
  shear_matrix <- function(){ matrix(c(2, 1.2, 0, 1), 2, 2) }
  # rotate_matrix <- function(x){ 
  #   matrix(c(1,1,1,1), 2, 2) 
  # }
  
  rotate_matrix <- function(x){
    matrix(c(cos(x), sin(x), -sin(x), cos(x)), 2, 2)
  }
  data %>% 
    dplyr::mutate(
      geometry = .$geometry * shear_matrix() * rotate_matrix(pi/20) + c(x_add, y_add)
    )
}

rotate_data_geom <- function(data, x_add = 0, y_add = 0) {
  shear_matrix <- function(){ matrix(c(2, 1.2, 0, 1), 2, 2) }
  
  rotate_matrix <- function(x) { 
    matrix(c(cos(x), sin(x), -sin(x), cos(x)), 2, 2) 
  }
  data %>% 
    dplyr::mutate(
      geom = .$geom * shear_matrix() * rotate_matrix(pi/20) + c(x_add, y_add)
    )
}
```


Create stack of monthly mortality data
```{r}
mortality_plot <- ggplot()

i <- 8
while(i >= 6){

  
  a <- mortality_data %>% 
    filter(month == i) %>% 
    st_as_sf() 
  
  box <- st_make_grid(a, n = 1) %>% 
    data.frame() %>% 
    st_as_sf() %>% 
    rotate_data(y_add = 10*y_int*(9 - i))
  
  a <- a %>%
    rotate_data(y_add = 10*y_int*(9 - i))
  
  mortality_plot <- mortality_plot +
    geom_sf(data = box, size = 1, color = "black", fill = "white") +
    #geom_sf(data = a, mapping = aes(fill = order_1), size = 2, color = "black") +
    geom_sf(data = a, mapping = aes(fill = 1000*mortality), size = .25) +
    geom_sf(data = box, size = 1, color = "black", fill = NA)
  
  i = i - 1
}
```


Polish stack of monthly mortality data
```{r}
mortality_plot <- mortality_plot +
  scale_fill_gradient2(low = "white", high = "firebrick3", midpoint = 0.2) +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 16),
        legend.position = "top",
        plot.caption = element_text(size = 12, face = "plain", hjust = .5),
        plot.background = element_blank(),
        panel.background = element_blank()) +
  labs(fill = "Deaths Per 1000 Individuals")

mortality_plot
```

