---
title: "Overlay Weights Figure"
output: html_document
date: "2022-10-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

Load Packages
```{r}
library(stagg)
library(tidyverse)
library(here)
library(raster)
library(sf)
library(gridExtra)
library(tigris)
library(ggpubr)
library(data.table)
```


Define Variables
```{r}
# Location selection
state_abb <- "CA"
county_geoid <- "06107"

# Color Scheme
polygon_fill <- "white"
cropland_fill <- "gold"
grid_color <- "grey"
w_area_fill <- "dodgerblue"
combined_fill <- "darkgreen"
```


Read in Data
```{r}
# Polygons for whole state
state_counties <- counties(state_abb)


# Polygon only of one county
county <- state_counties %>%  # We are using one county from the tigris package
  filter(GEOID == county_geoid) %>% 
  st_as_sf()


# Get the extent of the county with buffer
county_extent <- extent(extent(county) + .25)


# !!!These files are too large to be stored on github and must be manually copied to your directory's data folder!!!
cropland_raster <- crop(raster(here("data/cropland_NW_2015.tif")), county_extent) # Cropland to use as secondary weights



```


Run Stagg
```{r}
# Generate a table of era5 scale cropland weights
cropland_table <- secondary_weights(secondary_raster = cropland_raster, extent = county_extent) 

# Generate a table of overlay weights
overlay <- overlay_weights(polygons = county, polygon_id_col ="GEOID", secondary_weights = cropland_table) %>% 
  rename(combined_weight = weight)
```

Raster Plot
```{r}
# Transform fine resolution raster into a data frame for plotting
cropland_df <- as.data.frame(cropland_raster, xy = TRUE) %>% 
  filter(x >= min(cropland_table$x) - .125 & x <= max(cropland_table$x) + .125,
         y >= min(cropland_table$y) - .125 & y <= max(cropland_table$y) + .125) # Making the raster fit the grid


# Plot the Raster
ggplot(cropland_df) +
  geom_tile(aes(x,y, fill = cropland_NW_2015)) +             # Raster Data
  scale_x_continous(expand = c(0,0)) +
  scale_y_continous(expand = c(0,0)) +
  scale_fill_gradient(low = "white", high = cropland_fill) + # Setting color scale
  theme_void() +                                             
  theme(legend.position = "none",
        plot.background = element_rect(color = "black", size = 1)) +
  geom_sf(data = county,                 # Adding in a map of all counties for location context
            alpha = 0) +
  geom_tile(data = cropland_table, mapping = aes(x = x, y = y),   # Adding grid over the top to contextualize the image
            alpha = 0, size = 2, color = grid_color)  +      
  #coord_sf(xlim = c(xmin(county_extent),              # Cropping the image to raster
   #                 xmax(county_extent)),
    #       ylim = c(ymin(county_extent), 
     #               ymax(county_extent))) +
  theme(plot.background = element_blank())

```

Plot of Resampled Secondary Weights
```{r}
ggplot() +
    geom_sf(data = county, alpha = 0) +
  geom_tile(data = cropland_table, mapping = aes(x = x, y = y, alpha = weight), fill = cropland_fill, size = 2, color = grid_color) +
  scale_alpha(range = c(0, .5)) + # Define alpha range aesthetically (alphas corresponding to weights would all look empty)
  theme_void() +
  theme(legend.position = "none") 
```

Area Weights Plot
```{r}
# Same idea as previous image
ggplot() +
  geom_sf(data = st_shift_longitude(county), fill = polygon_fill, size = 1) +
  geom_tile(data = overlay, mapping = aes(x = x, y = y, alpha = w_area), fill = w_area_fill, size = 2, color = grid_color) +
  scale_alpha(range = c(0,.5)) +
  theme_void() +
  theme(legend.position = "none")
```

Cropland Weights Normalized by Area
```{r}
# Same plot as before but using weight instead of w_area
ggplot() +
  geom_sf(data = st_shift_longitude(county), fill = polygon_fill) +
  geom_tile(data = overlay, mapping = aes(x = x, y = y, alpha = combined_weight), fill = combined_fill, size = 2, color = grid_color) +
  scale_alpha(range = c(0, .5)) +
  #geom_label(data = overlay, mapping = aes(x = x, y = y, label = weight)) +
  theme_void() +
  theme(legend.position = "none") 
```

